In [65]:
import os
import sys
from google.colab import drive

# 1. Connect to your storage
drive.mount('/content/drive')

# 2. Teleport to your project root
PROJECT_PATH = '/content/drive/MyDrive/Krish_Naik_AI'
os.chdir(PROJECT_PATH)

# 3. Add your 'src' folder to Python's brain
if os.getcwd() not in sys.path:
    sys.path.append(os.getcwd())

# 4. Initialize the Logger (using your permanent __init__.py fix)
from src.datascience import logger

logger.info(">>> Environment Sync Complete. Ready for next stage! <<<")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[2026-03-17 15:52:52,273: INFO: 4046671116: >>> Environment Sync Complete. Ready for next stage! <<<]

In [51]:
import pandas as pd

data=pd.read_csv("artifacts/data_ingestion/winequality-red.csv")
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [52]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [53]:
data.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [54]:
data.shape

(1599, 12)

In [55]:
from dataclasses import dataclass
from pathlib import Path

@dataclass
class DataValidationConfig:
    root_dir:Path
    STATUS_FILE:str
    unzip_data_dir:Path
    all_schema:dict

In [56]:
from src.datascience.constants import *
from src.datascience.utils.common import read_yaml, create_directories

In [57]:
class ConfigurationManager:
    def __init__(
        self,
        config_filepath = CONFIG_FILE_PATH,
        params_filepath = PARAMS_FILE_PATH,
        schema_filepath = SCHEMA_FILE_PATH):

        self.config = read_yaml(config_filepath)
        self.params = read_yaml(params_filepath)
        self.schema = read_yaml(schema_filepath)

        create_directories([self.config.artifacts_root])

    def get_data_validation_config(self) -> DataValidationConfig:
        config = self.config.data_validation
        schema = self.schema.COLUMNS

        create_directories([config.root_dir])

        data_validation_config = DataValidationConfig(
            root_dir=config.root_dir,
            STATUS_FILE=config.STATUS_FILE,
            unzip_data_dir = config.unzip_data_dir,
            all_schema=schema,
        )

        return data_validation_config

In [58]:
import os
from src.datascience import logger

In [59]:
class DataValidation:
    def __init__(self, config: DataValidationConfig):
        self.config = config

    def validate_all_columns(self)-> bool:
        try:
            validation_status = None

            data = pd.read_csv(self.config.unzip_data_dir)
            all_cols = list(data.columns)

            all_schema = self.config.all_schema.keys()

            
            for col in all_cols:
                if col not in all_schema:
                    validation_status = False
                    with open(self.config.STATUS_FILE, 'w') as f:
                        f.write(f"Validation status: {validation_status}")
                else:
                    validation_status = True
                    with open(self.config.STATUS_FILE, 'w') as f:
                        f.write(f"Validation status: {validation_status}")

            return validation_status
        
        except Exception as e:
            raise e

In [60]:
try:
    config = ConfigurationManager()
    data_validation_config = config.get_data_validation_config()
    data_validation = DataValidation(config=data_validation_config)
    data_validation.validate_all_columns()
except Exception as e:
    raise e

[2026-03-17 15:14:56,409: INFO: common: yaml file: config/config.yaml loaded successfully]
[2026-03-17 15:14:56,415: INFO: common: yaml file: params.yaml loaded successfully]
[2026-03-17 15:14:56,420: INFO: common: yaml file: schema.yaml loaded successfully]
[2026-03-17 15:14:56,422: INFO: common: created directory at: artifacts]
[2026-03-17 15:14:56,425: INFO: common: created directory at: artifacts/data_validation]

In [64]:
import os

# 1. Find every 'logging.log' on this entire machine
!find /content -name "logging.log"

# 2. Check the one in your project specifically
print("\n--- Project Log Content ---")
!tail -n 5 /content/drive/MyDrive/Krish_Naik_AI/logs/logging.log

/content/drive/MyDrive/Krish_Naik_AI/logs/logging.log

--- Project Log Content ---
[2026-03-17 15:14:56,415: INFO: common: yaml file: params.yaml loaded successfully]
[2026-03-17 15:14:56,420: INFO: common: yaml file: schema.yaml loaded successfully]
[2026-03-17 15:14:56,422: INFO: common: created directory at: artifacts]
[2026-03-17 15:14:56,425: INFO: common: created directory at: artifacts/data_validation]
[2026-03-17 15:43:40,133: INFO: 347089208: The permanent fix is officially live!]